proxy_cache_path    /srv/http/blok45.art/imgproxy/cache levels=1:2 keys_zone=imgproxy_cache:100m max_size=10g inactive=365d use_temp_path=off;

server {
    listen 80;
    server_name images.blok45.art;

    location / {
        return 301 https://images.blok45.art$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name images.blok45.art;

    ssl_certificate /etc/letsencrypt/live/blok45.art/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blok45.art/privkey.pem;

    location /img/ {
        proxy_cache          imgproxy_cache;
        proxy_cache_valid    200 301 302 304 1h;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_ignore_headers Cache-Control Expires Set-Cookie;

        proxy_pass http://127.0.0.1:8080;

        add_header X-Cache-Status $upstream_cache_status;
    }

    location / {
        return 301 https://blok45.art;
    }
}

server {
    listen 80;
    server_name blok45.art;
    server_name www.blok45.art;

    location / {
        return 301 https://blok45.art$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.blok45.art;

    ssl_certificate /etc/letsencrypt/live/blok45.art/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blok45.art/privkey.pem;

    location / {
        return 301 https://blok45.art$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name blok45.art;

    charset utf-8;
    index index.php;
    root /srv/http/blok45.art/wordpress;

    ssl_certificate /etc/letsencrypt/live/blok45.art/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blok45.art/privkey.pem;

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }

    location = /xmlrpc.php {
        deny all;
    }

    location = /wp-config.php {
        deny all;
    }

    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

    location ~* ^/(?:favicon.ico|robots.txt)$ {
        root /srv/http/blok45.art/options;

        expires max;
        access_log off;
        log_not_found off;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(?:woff2?|ttf|otf|eot|css|js|jpg|jpeg|png|svg|gif|webp|avif|ico)$ {
        expires max;
        log_not_found off;
        add_header Cache-Control "public, max-age=2592000, immutable";
    }

    location ~ ^/artists/tokyo/? {
        return 301 https://blok45.art/artists/toyko/;
    }

    location ~ ^/artists/dizzy/? {
        return 301 https://blok45.art/artists/disp/;
    }

    location ~* \.php$ {
        try_files $uri =404;

        include fastcgi.conf;

        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
}
